// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://txodzbjpxmycwgyuqfzb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR4b2R6YmpweG15Y3dneXVxZnpiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyNTgyNDgsImV4cCI6MjA1NzgzNDI0OH0.lDoHpWaosKGGlBINEW-rsK9Ho4LABUbSyrD87czU9mM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);